// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_interview_app/test/features/todos/helpers/test_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_interview_app/core/network/http_client.dart' as _i2;
import 'package:flutter_interview_app/features/todos/domain/datasources/todo_remote_data_source.dart'
    as _i4;
import 'package:flutter_interview_app/features/todos/domain/entities/todo_entity.dart'
    as _i5;
import 'package:flutter_interview_app/features/todos/domain/repositories/todo_repository.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AppHttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppHttpClient extends _i1.Mock implements _i2.AppHttpClient {
  MockAppHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> get(String? url) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TodoRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoRemoteDataSource extends _i1.Mock
    implements _i4.TodoRemoteDataSource {
  MockTodoRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i5.TodoEntity>> getTodosPaged({
    required int? start,
    required int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodosPaged,
          [],
          {
            #start: start,
            #limit: limit,
          },
        ),
        returnValue: _i3.Future<List<_i5.TodoEntity>>.value(<_i5.TodoEntity>[]),
      ) as _i3.Future<List<_i5.TodoEntity>>);
}

/// A class which mocks [TodoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoRepository extends _i1.Mock implements _i6.TodoRepository {
  MockTodoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i5.TodoEntity>> getTodosPaged({
    required int? start,
    required int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTodosPaged,
          [],
          {
            #start: start,
            #limit: limit,
          },
        ),
        returnValue: _i3.Future<List<_i5.TodoEntity>>.value(<_i5.TodoEntity>[]),
      ) as _i3.Future<List<_i5.TodoEntity>>);
}
